### ISSUE TITLE
linter action is not running when submitting a PR

### ISSUE THREAD

**Issue by wernerkrauss** [n370/awesome-headless-cms#16]
When submitting a PR i get this error:

> actions/checkout@v2 is not allowed to be used in n370/awesome-headless-cms. Actions in this workflow must be: within a repository owned by n370.

A solution might be https://github.community/t/checkout-v2-error-actions-in-this-workflow-must-within-a-repository-owned-by-organization/136315/2

**Comment by n370** [comment]
Hey @wernerkrauss , thanks for all contributions I really appreciate them. Seems that I messed with the actions config. I chnaged it now so it looks like:

<img width="939" alt="Screen Shot 2020-10-12 at 11 37 05" src="https://user-images.githubusercontent.com/1547648/95758894-6207f280-0c7f-11eb-874f-445264fa2f59.png">

Previously I had "Allow local actions only" selected instead.

Would you try re-running the job once again?

**Comment by wernerkrauss** [comment]
Thanks, it seems to work  now, see #15
